### ISSUE TITLE
Fix hooks ordering

### ISSUE THREAD

**Issue by narze** [narze/react-useless#106]
I want to fix `useLess` at the top of the page and the list, to give the user the idea of useless hook.

and also `paUse` should be at the bottom of the list
because I don't want to see this face any time I visit the website...
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/248741/194128054-a8595359-b585-4add-bc0f-71f383372746.png">

**Comment by narze** [comment]
Maybe add an array to fix order
```javascript
const top = ["useLess"]
const bottom = ["paUse"]
```

and other hooks order alphabetically as they should be between the hooks in the top list and bottom list

**Comment by leomotors** [comment]
Closing this as completed in #110
