### ISSUE TITLE
[Mobile] Clicking hook name should close navigation pane

### ISSUE THREAD

**Issue by leomotors** [narze/react-useless#125]
When navigating on mobile, the pane does not close by itself.

It should close as we changed the hook. Do you agree?

![image](https://user-images.githubusercontent.com/59821765/194870595-4f29c755-7739-4137-bc25-4d57e45f9932.png)

**Comment by leomotors** [comment]
@tinarskii @ronnapatp @narze เห็นด้วยหรือไม่เห็นด้วยอย่างไรครับ ท่านสมาชิก

**Comment by ronnapatp** [comment]
เป็นไอเดียที่ดีเลยครับ ท่ า น ส ม า ชิ ก

**Comment by leomotors** [comment]
ใครที่จะทำอันนี้ (ผมไม่ทำ ไ ม่ ว่ า ง) จองมาได้เลยครับ

**Comment by tinarskii** [comment]
ทำเองเลยครับ ผ ม ไ ม่ ท ำ

**Comment by narze** [comment]
ส รุ ป มี ค น ท ำ ยั ง น ะ

**Comment by leomotors** [comment]
ไ ม่ มี เ ล ย ค รั บ  ใ ค ร อ ย า ก ท ำ บ อ ก ห น่ อ ย ค รั บ
ช่ ว ย กั น แ ก้ บั๊ ก

**Comment by tinarskii** [comment]
เดี๋ยวทำที่แปลว่า ใ ห้ ค น อื่ น ท ำ แ ท น เ ห อ ะ

**Comment by leomotors** [comment]
Fixed by #148
