### ISSUE TITLE
useForeignerTTS

### ISSUE THREAD

**Issue by narze** [narze/react-useless#153]
Receives text input and returns TTS url then read it.

Seems useful right? So make it more useless.

Detect and make it read as other language randomly by changing `lang=` query param
e.g. https://tts-api.vercel.app/api/tts?text=helloworld&lang=ja

**Comment by Myrfion** [comment]
Sounds very useless, could I make it?

**Comment by narze** [comment]
@Myrfion Can you make it by 24h from now? Since tomorrow I will attend a Hacktoberfest event and will open this issue for anyone

**Comment by Myrfion** [comment]
Hi, Sorry I was kinda busy last few days, just created the PR #158
