### ISSUE TITLE
useTheAnswerToTheUltimateQuestionOfLifeTheUniverseAndEverything

### ISSUE THREAD

**Issue by narze** [narze/react-useless#3]
returns the number 42
ref. https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#The_Answer_to_the_Ultimate_Question_of_Life,_the_Universe,_and_Everything_is_42

**Comment by narze** [comment]
Will be closed by #56, waiting for it to merge

**Comment by hgcassiopeia** [comment]
#130
