### ISSUE TITLE
Migrate all hook usage from App.tsx to hooks-usage folder

### ISSUE THREAD

**Issue by narze** [narze/react-useless#60]
From #58 we now automatically import components from `src/hooks-usage` folder so that editing `src/App.tsx` is not needed. We can gradually move hooks & components to that folder

See [src/hooks-usage/useLess.tsx](https://github.com/narze/react-useless/blob/main/src/hooks-usage/useLess.tsx) for example

**Comment by OozyGrub** [comment]
assign me please 🙋

**Comment by OozyGrub** [comment]
#98

**Comment by ronnapatp** [comment]
Close with PR: https://github.com/narze/react-useless/pull/98
