### ISSUE TITLE
[Q] Can we use @type/node in vite ?

### ISSUE THREAD

**Issue by sikkapat79** [narze/react-useless#68]
I don't know that can we use @type/node in vite or not.
Because I want to use some stuffs which are come with nodejs. such as crypto to random for truely random ain't like Math.random()

[Some of ref.](https://security.stackexchange.com/questions/84906/predicting-math-random-numbers) 😭

**Comment by narze** [comment]
You could try, but in my opinion true randomness seems to be useful 😂

**Comment by narze** [comment]
Can you emulate them without NodeJS and call it `useTrueRandom`? :trollface:

**Comment by sikkapat79** [comment]
Maybe not working.
But If it's work. It will come with expensive cost of setting.

**Comment by narze** [comment]
got an idea, call random API that claims true randomness 😂 
https://www.random.org/clients/http/api/

**Comment by sikkapat79** [comment]
> 

OK Krub. I'll implement with this one. It should be the best solution for now, hahaha.

**Comment by narze** [comment]
Will close this as it's irrelevant we don't need to add @type/node anymore
